.atom:    ""
.git:     ""
.gitlab:  "󰮠"
.github:  ""
.rvm:     ""
.Trash:   ""
.vscode:  ""
config:   "󱂀"
folder:   "󰉖"
hidden:   "󱪨"
lib:      ""
node_modules: "󰎙"
docs:     "󱋤"
.next:    ""
public:   "󰮜"
src:      "󱧷"
snippets:  "󱧽"
documents: "󱧷"
downloads: "󱃩"
music:     "󱍚"
pictures:  "󱃫"
desktop:   "󱋤"
videos:    "󱧻"
agetic:    "󰲃"
frontend:  "󰾰"
backend:   ""
portal:    "󰾔"
usb:       "󱊟"
pendrive:  "󱊟"