#Bashtop grayscale theme
#by aristocratos

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#00"

# Main text color
theme[main_fg]="#bb"

# Title color for boxes
theme[title]="#cc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#90"

# Background color of selected item in processes box
theme[selected_bg]="#ff" 

# Foreground color of selected item in processes box
theme[selected_fg]="#00"

# Color of inactive/disabled text
theme[inactive_fg]="#545454"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6d9aed"

# Cpu box outline color
theme[cpu_box]="#3b3b3b"

# Memory/disks box outline color
theme[mem_box]="#3b3b3b"

# Net up/down box outline color
theme[net_box]="#3b3b3b"

# Processes box outline color
theme[proc_box]="#3b3b3b"

# Box divider line and small boxes line color
theme[div_line]="#3b3b3b"

# Temperature graph colors
theme[temp_start]="#8FF0A4"
theme[temp_mid]=""
theme[temp_end]="#F66151"

# CPU graph colors
theme[cpu_start]="#8FF0A4"
theme[cpu_mid]=""
theme[cpu_end]="#F66151"

# Mem/Disk free meter
theme[free_start]="#8FF0A4"
theme[free_mid]=""
theme[free_end]="#F66151"

# Mem/Disk cached meter
theme[cached_start]="#8FF0A4"
theme[cached_mid]=""
theme[cached_end]="#F66151"

# Mem/Disk available meter
theme[available_start]="#8FF0A4"
theme[available_mid]=""
theme[available_end]="#F66151"

# Mem/Disk used meter
theme[used_start]="#8FF0A4"
theme[used_mid]=""
theme[used_end]="#F66151"

# Download graph colors
theme[download_start]=""
theme[download_mid]=""
theme[download_end]="#8FF0A4"

# Upload graph colors
theme[upload_start]="#30"
theme[upload_mid]=""
theme[upload_end]="##8cb9ed"
