#Bashtop grayscale theme
#by aristocratos

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#00"

# Main text color
theme[main_fg]="#bbbbbb"

# Title color for boxes
theme[title]="#cccccc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#909090"

# Background color of selected item in processes box
theme[selected_bg]="#ffffff" 

# Foreground color of selected item in processes box
theme[selected_fg]="#000000"

# Color of inactive/disabled text
theme[inactive_fg]="#545454"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6d9aed"

# Cpu box outline color
theme[cpu_box]="#3b3b3b"

# Memory/disks box outline color
theme[mem_box]="#3b3b3b"

# Net up/down box outline color
theme[net_box]="#3b3b3b"

# Processes box outline color
theme[proc_box]="#3b3b3b"

# Box divider line and small boxes line color
theme[div_line]="#3b3b3b"

# Temperature graph colors
theme[temp_start]="#3fc6d3"
theme[temp_mid]=""
theme[temp_end]="#ad46ff"

# CPU graph colors
theme[cpu_start]="#2ecc71"
theme[cpu_mid]="#f1c40f"
theme[cpu_end]="#e74c3c"

# Mem/Disk free meter
theme[free_start]="#ffffff"
theme[free_mid]=""
theme[free_end]=""

# Mem/Disk cached meter
theme[cached_start]="#3fc6d3"
theme[cached_mid]=""
theme[cached_end]=""

# Mem/Disk available meter
theme[available_start]="#ad46ff"
theme[available_mid]=""
theme[available_end]=""

# Mem/Disk used meter
theme[used_start]="#2ecc71"
theme[used_mid]="#f1c40f"
theme[used_end]="#e74c3c"

# Download graph colors
theme[download_start]="#0098ff"
theme[download_mid]="#657cff"
theme[download_end]="#ad46ff"

# Upload graph colors
theme[upload_start]="#00abf6"
theme[upload_mid]="#00bbea"
theme[upload_end]="#3fc6d3"
