[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x11\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\n\0\0\0\v\0\0\0\x17\0\0\0\f\0\0\0\x11)
contrastOpacity=188
contrastUiColor=#D9D9D9
disabledTrayIcon=false
drawColor=#73a824
drawFontSize=18
drawThickness=15
predefinedColorPaletteLarge=true
saveLastRegion=false
savePath=/home/troy/Pictures
showDesktopNotification=false
showHelp=false
showSidePanelButton=true
showStartupLaunchMessage=false
squareMagnifier=true
startupLaunch=true
uiColor=#3a3a3a
undoLimit=88
userColors=picker, #ea4335, #f18d00, #fbbc05, #8dc81a, #1e95ff, #9070e2, #0e0e11, #18181b, #ffffff

[Shortcuts]
TYPE_PIN=Shift+P
