#set -g mouse on

# Estilo de la barra de estado
set -g status-style "fg=#F7F7F7 bg=#383838"

# Bordes de los paneles
set -g pane-border-style fg=#424242
set -g pane-active-border-style fg=#ffffff

# Intervalo de actualización de la barra de estado (15 segundos en lugar de 900)
set -g status-interval 15  

# Longitud máxima de la barra de estado
set -g status-left-length 150
set -g status-right-length 150

# Barra de estado (izquierda y derecha)
# Mostrar un indicador cuando los paneles están siendo seleccionados
set -g display-panes-time 1000
set -g status-left '     #(tmux -V 2>/dev/null) ⏽   '
set -g status-right ' #S ⏽ 󰔂 #I·󰔃 #P     '
